### ISSUE TITLE
Apply for Job Button Not Working

### ISSUE THREAD

**Issue by leahlueck** [Automattic/WP-Job-Manager#1089]
The Apply for Job button is not working in Wordpress 4.8.  I have installed all the necessary components for WP Job Manager to run, but the "apply for job button" is not clickable.  I have compared all settings to previous job sites and they are set up correctly.  I only saw 2 settings for this portion which were "enter a URL or an email" and then in a different section "which do you want displayed under "application method".  Is there a setting missing?

http://www.employtennessee.com/job/caregivercna/

**Comment by tripflex** [comment]
In that example URL you provided, the button works fine. 

If you're having issues with it not working when an email address is entered in the `application` field (which is required for the button to show) ... then your problem is due to the JavaScript errors on your site, as the theme you're using, Jobify, uses a modal which requires JavaScript, and since you have JavaScript errors on your site, the modal will not load.  

You should contact Astoundify for support with your theme if you can't figure it out.

**Comment by vivekharidas009** [comment]
wp job manager apply for job button is not working. All my settings are fine 
what will be the problem? sharing my website link below please check it out and let me know the solution

http://designerrs.com/job/ux-trainer/

**Comment by jom** [comment]
@vivekharidas009 In the future, please visit https://wpjobmanager.com/support for support.

You have custom CSS that is forcing the application details to never show:
http://designerrs.com/?display_custom_css=css&ver=4.8.2
```
.application_details{
display: none !important;
opacity:0;
}
```

**Comment by yokemate** [comment]
the email address or URL is not decoded correct. Take a look at the following link, after I click the Apply for Job Button:

https://news.china.com.au/job/it-%e8%bd%af%e4%bb%b6%e6%b5%8b%e8%af%95%e3%80%81%e8%87%aa%e5%8a%a8%e5%8c%96%e3%80%81%e5%bc%80%e5%8f%91%e4%ba%ba%e5%91%98/

I was showed the: 

h&#117;&#097;&#046;yang&#064;&#097;mcs&#101;&#114;&#118;i&#099;&#101;s.&#111;r&#103;.a&#117;

which should be the email address; however, it is not showing correctly.

**Comment by yokemate** [comment]
![brave_jiN8hwDG4C](https://user-images.githubusercontent.com/90768487/133427318-c01938e9-6a96-4c52-955e-1eed22c9484d.png)

**Comment by yokemate** [comment]
surprisingly, after I copied the code here, it showed me the correct email address in github site.
