### ISSUE TITLE
Please enter your license key in the plugin list below to get updates for "WP Job Manager - Job Tags".

### ISSUE THREAD

**Issue by sandyallain** [Automattic/WP-Job-Manager#1136]
there is a bug... I cannot click on the link... i would like to put my license key.

**Comment by davoraltman** [comment]
Can you please try to select the plugin first (tick the box next to its name) inside WP Admin -> Plugins and then insert your license key and activation email and then hit enter. That should do the trick!

Also, this Github repo is for reporting bugs for the WP Job Manager core plugin - https://wordpress.org/plugins/wp-job-manager/. Nevertheless, I'd suggest always dropping by the forum first so that we can check it and provide support - https://wordpress.org/support/plugin/wp-job-manager

For receiving support for our paid add-ons (like Job Tags), please make sure to reach out to us via this form - https://wpjobmanager.com/support/

Thanks!
