### ISSUE TITLE
Non-job listings are detected by Google as jobs.

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/WP-Job-Manager#1156]
A user reports that Google is detecting business listings as job listings. Is there a way to change this so Google knows it's a business directory?

641441-zen

**Comment by tripflex** [comment]
Ahh didn't even think about that, and I know a lot of people are using Job Manager for non-job listings, like businesses or many other custom ones

**Comment by spencerfinnell** [comment]
I think if the theme changes the behavior that much the theme can remove the built in JSON-LD output and create their own.

**Comment by spencerfinnell** [comment]
There are also filters in place on the built in JSON-LD that would allow for the base type to be removed and other bits of info to be updated.

**Comment by jom** [comment]
Until we add a setting (?), we can recommend people override the filter:
`add_filter( 'wpjm_output_job_listing_structured_data', '__return_false' );`

cc: @bikedorkjon

**Comment by annezazu** [comment]
702059-zen

**Comment by jom** [comment]
Going to close this for now as it is expected behavior for WPJM. The filter should work fine for most people using it for non-job listings. If a significant number of additional users report this, let's create a new enhancement request for adding UI to disable JSON-LD. I feel if an edge case is fixable with a filter, I'd rather not clutter the settings.

**Comment by gaurav1984** [comment]
930952-zen
