### ISSUE TITLE
error message when submitting resume

### ISSUE THREAD

**Issue by belindawaldock** [Automattic/WP-Job-Manager#1280]
Hi
when submitting a resume i am getting the following error, although the cv is still being published.
Warning: Invalid argument supplied for foreach() in /home/softwarecornwall/public_html/wp-includes/class-wp-hook.php on line 277

i have just added an add on - WP Job Manager Emails - might this be causing the issue? im not sure if the error was happening before i installed as only noticed when testing submission to see if auto emails from new add on working.  
https://www.softwarecornwall.org/submit-resume/

its still working, but obviously an error doesnt look great - any advice much appreciated
thank you
belinda 
ps - liking the new widget to show jobs posts :) 

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi Belinda! This issues list is just for WP Job Manager core. I'm going to close the issue, but if you could, please send in a support request (https://wpjobmanager.com/support) and reference this issue. If you could look in your PHP Error log for more detailed error messages, that would also be helpful (the error that is shown don't provide many clues). One last thing to try would be to temporarily disable the other plugin and see if the error still shows.

**Comment by tripflex** [comment]
@belindawaldock 

What you are seeing showing up is not actually an error message, but as you can see in the message that was output, it is just a warning.  This is showing because your server configuration (hosting company) has PHP configured to output warnings on your site, which should be disabled for any production environments.  If you want to disable warnings from being output on your site, you will need to disable `WP_DEBUG_DISPLAY` in your `wp-config.php` file, and this will prevent warnings from being output on your site.

More information can be found at the link below, or by contacting your hosting company:
https://codex.wordpress.org/WP_DEBUG

Specifically, if you want to disable debug output on your site, you should have these values set in the wp-config.php file as defined in the documentation link above.

```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', false );
```

You must have `WP_DEBUG` true in order for `WP_DEBUG_DISPLAY` to be used, which should be set to false to prevent PHP warnings output on frontend of site.

This SHOULD BE DONE for any sites that are live (production) and not in development, to prevent potential security issues by outputting errors, as well as keeping a clean UI for your end users.

I believe this is being caused by my Emails addon due to the way that I had to remove the filters to override the default Resume Manager email from being sent, so it throws a warning regarding this ... but I will try and replicate this myself to confirm
