### ISSUE TITLE
Facebook in app browser not displaying jobs listings

### ISSUE THREAD

**Issue by chrisspin** [Automattic/WP-Job-Manager#1291]
#### Steps to Reproduce
1. open facebook in app browser
2. click on the link in facebook that leads to your jobs listing page
3. jobs listings are not shown

#### What I Expected
to see my job listings

#### What Happened Instead
job listings not shown

#### WordPress / WP Job Manager Version
WP Job Manager Version 1.29.2

**Comment by jom** [comment]
Is this a link to an individual job listing or the `[jobs]` shortcode page? What theme are you using? Please provide screenshots. This is probably a theme issue.

**Comment by chrisspin** [comment]
Hey Jom. Thx for the quick answer!
We're using [jobs] shortcode to display all available job listings. We're using a custom theme (one our dev team created).

**Comment by chrisspin** [comment]
Here is a video showing the issue:
https://youtu.be/JsxdOySOhiQ

**Comment by jom** [comment]
I'm not able to reproduce with Twenty-Seventeen theme. There must be something on your theme that stops JavaScript at some point in Facebook's in-app browser. It is weird because I thought iOS in-app browsers just used mobile Safari, where it works fine. Unfortunately, it isn't easy to see where it is breaking. If you're able to reproduce with a clean standard theme, like Twenty-seventeen, comment again and I'll reopen. 

![img_1907](https://user-images.githubusercontent.com/68693/35152211-49cf631a-fd19-11e7-8878-60ad784ddf70.PNG)
