### ISSUE TITLE
Allow redirects after a successful job edit

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#1298]
We currently let people redirect after job submission but not after editing a job. Maybe we can do this here-ish:

https://github.com/Automattic/WP-Job-Manager/blob/1.29.2/includes/forms/class-wp-job-manager-form-edit-job.php#L133-L140

Inspired by:

https://wordpress.org/support/topic/redirect-after-edit-job/

**Comment by wpfan2099** [comment]
@ Buddy - we should work on this!!!

**Comment by westaussie** [comment]
Thanks @aheckler for adding this here (wasn't sure if I should put it here instead of in the wordpress.org so put it there instead).

Wondering if by default the redirection should be set to go to the same place as the redirect after save (ie Job Dashboard), and be able to be overridden by a filter as needed? In my case I'm overriding the redirect location depending on logged in Role, so Admins see all Jobs and Employers/Candidates see their own respective Jobs.

Would definitely be great to have this in core rather than a plugin I think :-)

**Comment by aheckler** [comment]
@westaussie Looks like @jom has already coded up a fix for this here:

https://github.com/Automattic/WP-Job-Manager/pull/1299

... so that's where you might want to leave suggestions in the comments. :) Thanks!
