### ISSUE TITLE
Edit Company Logo from Backend Jobs Editor

### ISSUE THREAD

**Issue by erichboileau** [Automattic/WP-Job-Manager#1308]
#### Steps to Reproduce
1. Login as Employer
2. Go to backend jobs-editor and open any job
3. Attempt to change "Company Logo" (where "featured image" normally appears)

#### What I Expected
To be able to change the company logo (this option appears for Admin-level users and is accessible through the front-end jobs editor)

#### What Happened Instead
Doesn't appear.

#### Context / Source
This seems like a simple bug related to permissions for the back-end editor. I expect it's quite easy to fix, but I haven't looked into the code yet.

**Comment by asparatu** [comment]
I had the same issue with my theme and the reason why it was not showing is. You need to add theme support  for Featured Images. I notice none post and page didnt have also. It has nothing to do with the permission. Here is the fix for anyone that needs it. 
You need to edit your themes functions.php an add or update
`// Add theme support for Featured Images
	add_theme_support('post-thumbnails', array(
	'post',
	'page',
        'tribe_events',
	'job_listing' //for WP Job Manager
	));`
That should fix the issue.

**Comment by jom** [comment]
Closing this for now. Seems like there is a workaround. I'm also a bit confused about `Login as employer` as employers are not allowed in WP admin by default.
