### ISSUE TITLE
Resume visibility restrictions not working

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/WP-Job-Manager#137]
I have tried to restrict resume visibility using the following capabilities one-by-one:
- Administrator
- Subscriber
- Employer

In each case, I simply get "Sorry, you do not have permission to browse resumes". I am logged in with the correct role in each case.

A related question, would I be able to enter a few comma-separated roles in these permission boxes to allow a couple of roles to see resumes?

**Comment by kirusiya** [comment]
hi,, i can see resumes but wen try to enter resume page, dont let me, give page not found, i try do this
/**/
Try administrator, lower case, no white space or use a capability instead http://codex.wordpress.org/Roles_and_Capabilities.

Commas are not really needed because you can add custom caps using a plugin like https://wordpress.org/plugins/user-role-editor/ to multiple roles and use that instead.
/**/
but its not working

**Comment by richardmtl** [comment]
@kirusiya Please contact us here for support for the Resume add-on:

https://wpjobmanager.com/support/

This repository is for bug reports or enhancement requests for the core WP Job Manager plugin only, not for support requests, and not for help with our paid add-ons. Thanks!
