### ISSUE TITLE
Add DOM events for javascript hooking (such as for Google Analytics)

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1371]
Requested in 996475-zen for one of our add-ons, but this feels like it could be more generalized across the plugin *and* all the add-ons.

Contact Form 7 includes DOM events for easy JS functions:

https://contactform7.com/dom-events/

We could add them to the plugin for things such as job submissions, resume submissions, etc. In other words, for any time someone clicks a submit button.

**Comment by jom** [comment]
I think to actually benefit from this we'll need to transition the submission form to ajax/background submission (like Contact Form 7). Otherwise the Google/other requests could be immediately cancelled when the form submit is fired. We have two places where we currently use Ajax: file uploads for logged in users; `[jobs]` shortcode with filters shown. The `[jobs]` shortcode does trigger a DOM event for both starting to update the jobs listed and after jobs are updated:
```js
$( '.job_listings' ).on( 'update_results', function() {
   // do something when an update is triggered.
} );
$( '.job_listings' ).on( 'updated_results', function() {
   // do something after listings are updated.
} );
```

I'm going to defer this until we implement background form submission.
