### ISSUE TITLE
Add role dropdown selection on new user registration.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#1397]
On our WP Job Manager demo, we use the [Jobify](https://themeforest.net/item/jobify-wordpress-job-board-theme/5247604) theme, which has the ability to choose Candidate or Employer as the default role upon new user registration:

![register_as](https://user-images.githubusercontent.com/7585054/37712854-7bec2fc0-2ceb-11e8-8a86-2b23ea86d7cb.png)

Is this something we can implement into core WPJM? It seems like a really nice feature, and if we're showing it on our demo site, it seems a bit misleading for it to be a part of a theme (which isn't even ours.)

Requested in 1032459-zen

**Comment by alexsanford** [comment]
Currently, WPJM actually [doesn't supply a login/registration form at all](https://wpjobmanager.com/document/registration-login-page/). As you said in the ticket, user accounts are created when a user submits a job/resume/etc and the role is assigned based on the context.

Maybe it would be helpful to get some more information from the user? It would be interesting to know what their use-case is, and why the current functionality doesn't meet their needs. We might be able to come up with an even better way to solve their problem 🙂 

Otherwise, I would say given the fact that we don't have a generic login/registration form, probably this is not a feature we want to take on at this point.

**Comment by jenhooks** [comment]
Oops! I should have realized this -- WPJM designates a user as the `Employer` role if they submit a job first, or a `Candidate` if they submit a resume first (if Resume Manager is installed), is that right?

**Comment by spencerfinnell** [comment]
@jenhooks Correct. However there were lots of requests to allow this process to happen without actually submitting a listing. A potential employer may want to register to contact candidates, and the opposite. Allowing a role selection (instead of defaulting to Subscriber) allows the site owner to target those users more directly -- such as tailoring navigation menu items to the current user.

**Comment by taliaShwartzBB** [comment]
i am also intrested in such option, any update with this?
