### ISSUE TITLE
[job_dashboard] not working with add_rewrite_rule custom URL

### ISSUE THREAD

**Issue by imfaisalkh** [Automattic/WP-Job-Manager#1567]
I'm using `[job_dashboard]` shortcode on a custom URL which I've created with `add_rewrite_rule` like this:

```
 // 1: Register custom URL
  function custom_rewrite_basic() {
    global $wp_rewrite;
    add_rewrite_rule('^dashboard/(.*)/?', 'index.php?is_dashboard=true&dashboard_page=$matches[1]', 'top');
    $wp_rewrite->flush_rules(true);  
  }
  add_action('init', 'custom_rewrite_basic');

  // 2: Register custom query parameters
  function rewrite_add_var( $vars ) {
    $vars[] = 'is_dashboard';
    $vars[] = 'dashboard_page';
    return $vars;
  }
  add_filter( 'query_vars', 'rewrite_add_var' );

  // 3: Set the template
  function set_custom_template() {
    if( get_query_var( 'is_dashboard' ) ) { // is user accessing a dashboard page?
        return get_template_part( 'dashboard/manage-jobs/' );
    }
  }
  add_action( 'template_redirect', 'set_custom_template' );
```

Now, if I visit the url `/dashboard/manage-jobs/` the `[job_dashboard]`  shortocode is working fine and and displays a table with user posted jobs, the issue occurs when I click on any job dashboard actions i.e. Edit, Mark Filled, Duplicate, Delete. When I click on any of these action the page reloads and nothing occurs, not even any error message.

However, if I use the `[job_dashboard]` on a regular page (created via wordpress admin panel) the job dashboard actions works fine.

Can you tell me what is the issue here and how can I make these actions work with my custom URL?

**Comment by iamgabrielma** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. If you need help with the default functionality and you have an active license please head here: https://wpjobmanager.com/support, otherwise we support the free WP Job Manager plugin in our WordPress.org forums, here: https://wordpress.org/support/plugin/wp-job-manager/

In any case, note that we do not offer customization support, and we can just provide support for the product as it is, out of the box.
