### ISSUE TITLE
Fatal Error when attempting to add new Job Listing

### ISSUE THREAD

**Issue by Whartan-Jeers** [Automattic/WP-Job-Manager#1676]
#### Steps to Reproduce
1. Log into Wordpress
2. Go to Job Listing
3. Try to add new listing

#### What I Expected
New listing window to appear

#### What Happened Instead
Got Fatal error: Uncaught Error: Call to a member function current_user_can_access_publicize_data() on null in /srv/bindings/246c701ad8d54926b82c6cf2e13cc6af/code/wp-content/plugins/jetpack/_inc/lib/core-api/wpcom-fields/post-fields-publicize-connections.php:118

#### WordPress / WP Job Manager Version
WordPress 5.0.3 

#### Browser / OS Version
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) in Windows 7.

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/25985864/51912688-e24ecd00-23a2-11e9-92a7-feede9d6387b.png)

**Comment by richardmtl** [comment]
Hi! Since this issue appears to be limited to your site (we have no other similar reports), can you either contact us here if you have a paid subscription for one of our add-ons:

https://wpjobmanager.com/support/

If you don't, then please open a new thread in the support forum:

https://wordpress.org/support/plugin/wp-job-manager/

Please include your site's URL. Thanks!
