### ISSUE TITLE
Problems with WP Job Manager since update, version 1.32.2

### ISSUE THREAD

**Issue by akshaybatra1** [Automattic/WP-Job-Manager#1694]
Since the new update of WP Job manager, not able to Post a job.after clicking on submit listing page, it redirects and says "The link you followed has expired." Attaching the video as a reference.
http://recordit.co/VhRTnKsDeS

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support. This is probably because your theme has overridden the `job-preview.php` template. That template needs to be updated. Specifically, this needs to be added after the `<form ...>` tag:
```
	<?php
	/**
	 * Fires at the top of the preview job form.
	 *
	 * @since 1.32.2
	 */
	do_action( 'preview_job_form_start' );
	?>
```

**Comment by akshaybatra1** [comment]
@jom - thanks a lot.. it works now !!

**Comment by nseelen** [comment]
@jom I'm having the same problem while using the jobify theme. I updated the job-preview.php template in the plugin, but I don't see any file with this name in my theme directory. Any thoughts on how to proceed?

**Comment by richardmtl** [comment]
@nseelen please contact us here, if you have a paid license for one of our addons:

https://wpjobmanager.com/support/

Otherwise, please post in the forums:

https://wordpress.org/support/plugin/wp-job-manager/
