### ISSUE TITLE
Wrong posts array from cached query in get_job_listings() 

### ISSUE THREAD

**Issue by anastis** [Automattic/WP-Job-Manager#1784]
https://github.com/Automattic/WP-Job-Manager/blob/585e5cb5ca8332797909c3b370e0cfa394012967/wp-job-manager-functions.php#L182

The caching logic  of `get_job_listings()` completely disregards the other cases of the `'fields'` parameter (`ids`, `id=>parent`), and always populates the WP_Query::posts array with WP_Post objects unconditionally, breaking any existing code that assumes that e.g. an array of integers is returned.

The  side effects are only observable on the second and subsequent runs of e.g. `get_job_listings( [ 'fields' => 'ids' ] )`.

**Comment by manzoorwanijk** [comment]
That is not the case. If you look carefully, the cached result set is different for every unique query because every query is [hashed](https://github.com/ovidiul/WP-Job-Manager/blob/1.33.4-beta-2/wp-job-manager-functions.php#L167-L168) (making it unique).

So, if you pass `'fields' => 'ids'` in one call and `'fields' => 'all'` in another call, the results will be from two different cashed sets if cached.

**Comment by anastis** [comment]
@manzoorwanijk what you say is true, and what I say is also true.
The problem isn't with the actual caching of the query, but with the code that sets up the WP_Query object after fetching the json-stored transient.
You see, `get_post()` shouldn't be applied on `$cached_query_posts->posts` when `'fields' => 'ids'` because  it's an array of posts, not WP_Post objects.

**Comment by manzoorwanijk** [comment]
Aha! Got it. Yes, that's is a problem. Will try to work in it for a fix.

**Comment by manzoorwanijk** [comment]
There you go!

**Comment by jom** [comment]
Reopening for final fix in #1887
