### ISSUE TITLE
[REST API] Cannot change the author of the job

### ISSUE THREAD

**Issue by kelvkong** [Automattic/WP-Job-Manager#1809]
#### Steps to Reproduce
1. Create a job via REST API
2. Set all 'author' & 'post_author' and also '_job_author' inside the 'fields' element to the author ID

Sample Request:
```
{  
   "job-categories":[  
      1
   ],
   "platform_source":[  
      1
   ],
   "status":"publish",
   "slug":"Test-slug-1",
   "title":"Test Title",
   "content":"Test Content 1",
   "comment_status":"open",
   "ping_status":"closed",
   "format":"standard",
   "meta":[  

   ],
   "sticky":false,
   "fields":{  
      "_job_author":"89",
      "_job_location":"Venue 1"
   },
   "author":89,
   "post_author":"89"
}
```

#### What I Expected
The job author should be the user with the author ID

#### What Happened Instead
The job author is the integration user who creates the job via REST API

#### WordPress / WP Job Manager Version
Wordpress v5.22
WP Job Manager 1.33.2

**Comment by jom** [comment]
`_job_author` is just a faux field to fill `post_author` so it doesn't do anything. 

On the REST API request, `author` is what you should use:
https://developer.wordpress.org/rest-api/reference/posts/#arguments-4

It looks like this isn't exposed  because we haven't added `author` to the CPT's `supports` argument. 

This snippet should work until we do:
```php
add_filter( 'register_post_type_job_listing', function( $args ) {
  $args['supports'][] = 'author';
  
  return $args;
} );
```
