### ISSUE TITLE
Upload and Insert image

### ISSUE THREAD

**Issue by ecjoin** [Automattic/WP-Job-Manager#1820]
I'm using WP Job manager plugin
and I want my website user can upload image via job submission page.
(I want to insert the image in the job description editor, with the text)
I'd try to work with the tinymce editor (wp-includes/class-wp-editor.php)
and I've add the upload.php(image upload handler)
And I've add the upload tab at image dialog successfully
However it keeps showing"HTML Error 404" when adding image
The upload function doesn't work.
Afterwards I change to the file picker function instead,
the image appears inside the editor but it disappears after submit.
There is nothing UPLOADED to my server.

Can anybody help on this?
Nomatter image upload nor file picker....or even change the editor,
I just want to add some image between text (NOT attachment)
Thanks a lot.

**Comment by richardmtl** [comment]
Hi,

This repo is for reproducible bug reports or enhancement requests, not support requests. If you have one of our paid add-ons, please send us a ticket here: 

https://wpjobmanager.com/support/

Otherwise, please start a thread here:

https://wordpress.org/support/plugin/wp-job-manager#postform

Thanks!
