### ISSUE TITLE
Job Listing Expiry Date Removed After Editing

### ISSUE THREAD

**Issue by daisymae6580** [Automattic/WP-Job-Manager#1822]
#### Steps to Reproduce
1. Post Job which includes an "Listing Expiry Date"
2. Edit Job (any field, it doesn't matter)
3. Save Job
4. If you look at the Job again, or even just on the "All Jobs" list, the expiry date is now missing.

#### What I Expected
The expiry date to remain as is unless directly changed. 

#### What Happened Instead
The date disappears completely when a job is edited in any way.

#### WordPress / WP Job Manager Version
WP Version 5.2.2 / WP Job Mgr Version 1.33.3

#### Browser / OS Version
Tested in both Firefox 67.0.4 & Chrome 75.0.3770.100 / MacOS Mojave 10.14.5

#### Screenshot / Video
https://www.loom.com/share/21543049fa1f42dabda573642d24c8e1

**Comment by richardmtl** [comment]
Hi!

From your video, you are editing a job listing that has already expired; note that the button says Publish, and not Update, when you first go into the job listing. When you do that, you are no longer updating it, you are Publishing it again. That is why the expiry date is being removed; you are effectively re-publishing the new listing, and since you are not defining a (future) expiry date, the past expiry date is removed. This does not happen when editing jobs that are not expired. I do not consider this a bug; this is how we let people re-publish previously-expired jobs. You can think of the "expired" status as being similar to "draft". Hope that clarifies things!

**Comment by daisymae6580** [comment]
Makes perfect sense, thank you so much for your quick response!
