### ISSUE TITLE
Resume/Profile

### ISSUE THREAD

**Issue by TheJobWork** [Automattic/WP-Job-Manager#1834]
Why is the resume created not attachable to the profile of the member...cant understand that this is even missing.

**Comment by richardmtl** [comment]
Hi!

This repository is for reproducible bug reports or feature requests for our core WP Job Manager plugin. If you are having issues with the Resume add-on, please contact us here:

https://wpjobmanager.com/support/

Otherwise, for help with the core plugin, you can open a thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!
