### ISSUE TITLE
Apply to Jobs 

### ISSUE THREAD

**Issue by AmineBAIK1** [Automattic/WP-Job-Manager#1838]
Hello, 
I am using wordpress with buddyboss platform and buddyboss theme all with last version. 
And also WP Job manager with the last version. 
When i add apply to jobs to the menu ! i have this empty page is it normal?
![apply](https://user-images.githubusercontent.com/46829598/62086876-132f9200-b260-11e9-9911-3798831cb2a8.jpg)

**Comment by TheJobWork** [comment]
t sur c pas buddy boss plutot kil faut contacter ?

**Comment by richardmtl** [comment]
Hi!

This repository is for reproducible bug reports or feature requests for our core WP Job Manager plugin. If you are having issues with the Resume add-on, please contact us here:

https://wpjobmanager.com/support/

Otherwise, for help with the core plugin, you can open a thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!

**Comment by TheJobWork** [comment]
Amine t sur t au bon endroit la pour c WP job manage ici  ...
