### ISSUE TITLE
Jobs Tags 

### ISSUE THREAD

**Issue by AmineBAIK1** [Automattic/WP-Job-Manager#1839]
Hello, 
I am using wordpress with buddyboss platform and buddyboss theme all with last version. 
And also WP Job manager with the last version. 
When i activate Jobs tags as a plugin the layout is broken or misfunctionning. Is it a bug ?
![tags](https://user-images.githubusercontent.com/46829598/62087064-a799f480-b260-11e9-884b-d73a245d055c.jpg)

**Comment by richardmtl** [comment]
Hi!

This repository is for reproducible bug reports or feature requests for our core WP Job Manager plugin. If you are having issues with the Resume add-on, please contact us here:

https://wpjobmanager.com/support/

Otherwise, for help with the core plugin, you can open a thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!

**Comment by TheJobWork** [comment]
well thats a reproducible bug to me. ..

**Comment by richardmtl** [comment]
@TheJobWork As I mentioned ,if the issue is with one of our add-ons (you mentioned Job tags), then please contact us here:

https://wpjobmanager.com/support/
