### ISSUE TITLE
WPJM 1.33.4 breaks functionality of "Download Attachments" plugin

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1843]
Reported in 2240943-zen

Steps to reproduce:

1) On a site with WPJM 1.33.3, install and activate https://wordpress.org/plugins/download-attachments/
2) In Settings -> Attachments, make sure "All users" and "job_listing" are selected, and Save
3) Create new job listing from Job listings -> Add New
4) In the Download Attachments metabox, add a PDF file, and click Save in that same meta box. 
5) Publish the job listing; refresh the Edit Listing page in WP-Admin; note that the PDF attachment is still there
6) Update to WPJM 1.33.4
7) Follow steps 4 and 5 again
8) After publishing and refreshing, note that the PDF attachment is no longer there in WP-Admin for the job listing.

**Comment by manzoorwanijk** [comment]
It took me a few hours to investigate the issue, I finally found that the bug was introduced by #1798. That PR introduced the usage of `wp_update_post` inside `save_post` callback and removed the direct database access which had a purpose. Although it removes its own callback from the hook before calling `wp_update_post` but it can't do so with other plugins' callbacks.
So, if any faulty plugin like Download Attachments [modifies](https://plugins.trac.wordpress.org/browser/download-attachments/tags/1.2.23/includes/metabox.php#L78) the global `$_POST` in the callback and [relies on the same modified data](https://plugins.trac.wordpress.org/browser/download-attachments/tags/1.2.23/includes/metabox.php#L71), then it won't be the same in second call fired by `wp_update_post`. It can in fact affect other plugins that rely on the global `$_POST`.

**Comment by manzoorwanijk** [comment]
I have created a corresponding support topic [here](https://wordpress.org/support/topic/bug-in-save_post-hook-callback/).

**Comment by richardmtl** [comment]
Thanks for your investigative work, @manzoorwanijk !

**Comment by SallyMoo** [comment]
Hi, Following for updates. Thanks.

**Comment by jom** [comment]
@manzoorwanijk Thank you for digging into that. I've reverted that change for now in #1876. Slated for 1.34 (no ETA yet).
