### ISSUE TITLE
Build in search caching problem

### ISSUE THREAD

**Issue by Braehler** [Automattic/WP-Job-Manager#1857]
#### Steps to Reproduce
.you search fo city A you get the results for city A. But when you do a second search, for City B, you get the results of city A. A third search for City C will get the results of City B and so on

#### What I Expected
When searching for city A, get the results of city A,
Then searching for city B and get the results of city B

#### What Happened Instead
Searching for city A get the result of city A,
Searching for city B leads to the result of city A

#### WordPress / WP Job Manager Version
Word Press 5.2.2
WPJM: 1.33.3 but this also happens with 1.33.4

#### Browser / OS Version
FF 68-0.1 64bit
Chrome: 76.0.3809.100 64bit

**Comment by richardmtl** [comment]
Hi! I believe I've seen this happen before, and I'm pretty certain it's being caused by the theme. Since this isn't something that I can reproduce on my end, please either send in a support request here if you have a valid license for one of our addons:

https://wpjobmanager.com/support/

and if you don't, then please open a thread here:

https://wordpress.org/support/plugin/wp-job-manager/

If we determine that this is indeed a bug with our plugin, we can re-open this issue or open a new bug report for our developers. Thanks!

**Comment by Braehler** [comment]
Hi, this is not related to the theme, I was already in contact with them before opening this issue here. Maybe its caused by the WC Paid Listing. I´ll open a ticket at your support.There are also two open threads on the support forum
https://wordpress.org/support/topic/build-in-search-cache-problem/
https://wordpress.org/support/topic/the-cached-searching-overwrites-the-search-from-custom-form/
