### ISSUE TITLE
Listing view to grid view

### ISSUE THREAD

**Issue by kamalkhu** [Automattic/WP-Job-Manager#1861]
I can't seem to find the option to change the jobs from listing to a grid layout. Earlier I had it, but after I migrated my website to an other webhost it went gone.

https://fiduzia.nl/vacatures/

Here you can see it's only a listing.

**Comment by richardmtl** [comment]
This repository is for reproducible bug reports or feature requests for our core WP Job Manager plugin. If you are having issues with one of our add-ons, please contact us here:

https://wpjobmanager.com/support/

Otherwise, for help with the core plugin, you can open a thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!
