### ISSUE TITLE
Resume ID

### ISSUE THREAD

**Issue by AmineBAIK1** [Automattic/WP-Job-Manager#1862]
My question is simple: 
How to get Resume ID from a User ID 
- User can post only 1 resume.

**Comment by richardmtl** [comment]
This repository is for reproducible bug reports or feature requests for our core WP Job Manager plugin. If you are having issues with one of our add-ons, please contact us here:

https://wpjobmanager.com/support/

Otherwise, for help with the core plugin, you can open a thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!
