### ISSUE TITLE
Fixing "External Link" redirect

### ISSUE THREAD

**Issue by shaleedt** [Automattic/WP-Job-Manager#1864]
How to redirect users to external link site when they click on the job title on job listing page. I don't want the "single job page" to open for external sites. Instead, I want them to be redirected right away. Any ideas? 

<!--
Thanks for contributing to WP Job Manager! Pick a clear title ("Improve client-side UI validation") and proceed.

PLEASE NOTE
- These comments won't show up when you submit the issue.
- Everything is optional, but try to add as many details as possible.
- If requesting a new feature, explain why you'd like to see it added.
- This issue tracker is not for support. If you have questions about WP Job Manager, please visit the support forum: https://wordpress.org/support/plugin/wp-job-manager
- Do not report potential security vulnerabilities here. For responsible disclosure of security issues and to be eligible for our bug bounty program, please submit your report via [the HackerOne portal](https://hackerone.com/automattic).

Helpful tips for screenshots:
https://en.support.wordpress.com/make-a-screenshot/

**Comment by richardmtl** [comment]
Hi!

This repository is for reproducible bug reports or feature requests for our core WP Job Manager plugin. If you are having issues with one of our add-ons, please contact us here:

https://wpjobmanager.com/support/

Otherwise, for help with the core plugin, you can open a thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!
