### ISSUE TITLE
WC Paid Listings — Remove package from user?

### ISSUE THREAD

**Issue by DennisNDean** [Automattic/WP-Job-Manager#1875]
Is there a way to delete a package from a user's account? For instance, we had an unlimited package we were using for beta testing — how do I remove it from our beta testers' accounts now that the beta is over? Deleting the purchase in WooCommerce doesn't do it.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support (especially with our official paid extensions), please visit https://wpjobmanager.com/support.

**Comment by Hastibe** [comment]
@jom -- we are also interested in knowing the answer to this for similar reasons. We can delete the order for the package, but then this will expire the job posts attached to it as well as eliminate any other products that were part of the order, so that doesn't work, either.

We will also reach out to support about this, and I strongly encourage adding more documentation for the WC Paid Listings plugin (about this, the two day grace period on job packages, the limitation to only add a quantity of one for each type of job package to the cart, etc.), as that would be really helpful (and reduce the support burden, too, I hope!).

**Comment by Hastibe** [comment]
@DennisNDean - oh, also, what solution did you end up finding for this? We would be grateful to know!

**Comment by DennisNDean** [comment]
it’s under users > listing packages - hope this helps!

**Comment by Hastibe** [comment]
@DennisNDean - oh, haha--wow, that does help, thank you so much!
