### ISSUE TITLE
A "Keywords" field still does not work properly (also with custom search form) [1.34.0]

### ISSUE THREAD

**Issue by kibus90** [Automattic/WP-Job-Manager#1891]
Hi,

I just updated WP Job Manager to 1.34.0 Beta Version to check is there everything already good with the "keywords" field. Unfortunately the error still occurs.

What it does mean?

If I write on my homepage in "keywords" word "driver" and press Enter, then I get job listings, but the field "keywords" is not filled in with my kewyord. It is happening after refresh page.

If I will write e.g. "cook" in keywords and go to "Job listings", the field keywords after a few seconds is filled by "cook".

Can you check it before an official relase?

**Comment by jom** [comment]
@kibus90 I'm not quite following. On the `[jobs]` page you're putting in "cook" into the keyword field, but I'm not sure I follow the steps after or expected result.

Note: If you expect "cook" to be cleared after refresh, some browsers persist the form fields (like Firefox). Holding down the shift key might prevent this behavior from happening.

**Comment by jom** [comment]
Closing for now, but feel free to comment again with more information.

**Comment by andreilupu** [comment]
I think that this issue has a valid point because there are a few problems with the filtering form and its event binding.

At this point, the plugin assumes that the filtering form is inside the wrapper of the `.job_listings` https://github.com/Automattic/WP-Job-Manager/blob/master/assets/js/ajax-filters.js#L123. 
But this is not always true. For example, a WordPress theme, can use the filters template part inside a widget, or a different template like a homepage, without having the listings result in place(will redirect to listings page with [jobs] on submit).

Another thing that contributes to this issue is the fact that the [localStorage key](https://github.com/Automattic/WP-Job-Manager/blob/master/assets/js/ajax-filters.js#L44 ) depends on the selected Listings page ID and in the case presented above, a `form.job_filters element ` will persist the form to an index on the homepage, but submit and redirect to a different page with a different stored form.

![search-bug](https://user-images.githubusercontent.com/1893980/65760989-b0a32700-e126-11e9-934b-699f4e940fd3.gif)

Also, you can have no Listings page selected in WPJM settings, and it can fall back on a general archive template. In this case, the `get_session_storage_key` function will return a different key, based on the WP_Query posts loop, not on the selected Listings page.

But enough with problem hunting, as solutions I think that a few things should change:

* The event binding could use a refactor, right now the flow is: Look for the `.job_listings` -> search for `.job_filters` within its children elements and bind events or persist the form values.
Maybe we can make it simpler by handling events for these elements on their own, without making them dependent on each other.
* The key name for the localStorage entry could be constructed with the page URL instead of post ID. Very helpful for a `form.job_filters` outside of `.job_listings` because we can use the `action` attribute and persist the form for the future page.

I also have a PR ready, but I would love to chat further if this makes sense and if there are different alternatives.

**Comment by jom** [comment]
@andreilupu These feel like outside of the original issue, but I'll put feedback on the PR.

**Comment by Braehler** [comment]
any updates on this?
