### ISSUE TITLE
Mark as Filled action generates incorrect messages with paginated jobs on job dashboard

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1912]
From https://wordpress.org/support/topic/is-anyone-facing-this-problem-with-filled-or-non-filled-positions/

Screencast: https://streamable.com/i8n7y

Steps to reproduce:

1) Make sure you have enough jobs on your jobs dashboard that they are paginated at least to a page 2.
2) On the jobs dashboard, mark a job as filled; you will get the correct "X has been filled" message.
3) Click on the "2" in the pagination at the bottom of the jobs list.
4) You'll see a random "This position has already been filled." error message at the top.
5) Click again back to page 1, you'll see the same "This position has already been filled." message.
6) Click the "mark as unfilled"; you'll see the correct "X has been marked as not filled." message.
7) Click once again on the "2"; you'll see a random "This position is not filled." message at the top.
8) Click again back to page 1, the same "This position is not filled." message is still there.

These erroneous messages are confusing. :)

**Comment by ibiza69** [comment]
Hi, after updating to **version 1.34.1**, problems are not solved. Same exactly problems with positions filled and non filled as in version 1.34.0.

Any feedback or information? Do you think this will be solved some day?

Thank you.

**Comment by richardmtl** [comment]
Hi @ibiza69 ; as you can see above, there's been no work done on this yet, which is why it wasn't fixed in 1.34.1. When there's work on it, you'll see it here. Thanks!

**Comment by ibiza69** [comment]
Hi Richard and thanks for your answer, but you know that there are companies publishing jobs and that can´t control their backoffice (filled and none filled possitions) and that those errors confuse them, as if any of them select filled, then they will have those terrible messages all the time, untill there is an update from your company? Thank you

**Comment by JuanchoPestana** [comment]
Hey @richardmtl and @jom ! 
This PR should take care of the issue... Please let me know your thoughts and if there's anything else I could do to help! Thanks!

**Comment by ibiza69** [comment]
Hi Richard, un 17, Oct 2019, you created this pending bug, but today it´s 14 Jan 2020, and hasn´t being fixed. Could you please update with information? This is creating us many problems with companies publishing job offers and we have to explain them why this isn´t working and that we are waiting for an update from developer, but 3 months after, is like too much, no? Thanks for all and happy new year!

**Comment by ibiza69** [comment]
Hi, any update with this bug, after somany months awaiting for a solution? Thanks in advance.

**Comment by ibiza69** [comment]
Hi, after updating to version **1.34.2**, problems were **not solved**. Same exactly problem with "**positions filled and non filled**" as in versions **1.34.1** and **1.34.0**

Richard, I hope you can excuse me, but it's desperate to see these problems continue and that the companies that publish their job offers on our pages face. They write to us again and again to our support, requesting a solution and we can not tell them absolutely nothing, because we depend on you and your team to solve it, but we have been waiting for a solution since October 2019, and after 2 plugin updates, there wasn´t a remedy.

![1](https://user-images.githubusercontent.com/13764937/83323127-094e3500-a25d-11ea-9042-eeaacee37670.jpg)

![2](https://user-images.githubusercontent.com/13764937/83323142-15d28d80-a25d-11ea-9bde-b3f79531a2e6.jpg)

![3](https://user-images.githubusercontent.com/13764937/83323144-1d923200-a25d-11ea-872c-5d0c66855a84.jpg)

![4](https://user-images.githubusercontent.com/13764937/83323146-2420a980-a25d-11ea-88b6-c93a366445b0.jpg)

![5](https://user-images.githubusercontent.com/13764937/83323165-44506880-a25d-11ea-8318-e241aa3306b8.jpg)

![6](https://user-images.githubusercontent.com/13764937/83323169-49adb300-a25d-11ea-9506-fcd12d4e2c66.jpg)

Any feedback or information? Do you think this will be solved some day?

Thank you.
