### ISSUE TITLE
Action to give users a free job package

### ISSUE THREAD

**Issue by AlexxxH** [Automattic/WP-Job-Manager#1991]
**Is your feature request related to a problem? Please describe.**
I would like to give the user the option of submitting a job for free, without having to go through the checkout/ payment stages (which is very off-putting for users). By adding this action, this enables developers to add a code snippet to give the user a free job package. 

**Describe the solution you'd like**
I would like the following action added to Line 691 of /includes/class-wp-job-manager-email-notifications.php:

do_action('submit_job_before_preview_custom');

**Describe alternatives you've considered**
I have added this to my plugin files but this is overwritten by every update.

**Additional context**
This is a very quick and easy addition to the code.

**Comment by jom** [comment]
Hi there! This GitHub Issues is for reporting bugs and feature requests for the core plugin. For support or to make requests for our paid extensions, please visit https://wpjobmanager.com/support.

**Comment by AlexxxH** [comment]
Hi Jom, I was not asking for support or for a feature request to the paid extensions, I was just asking for an action to be added to the code :)

**Comment by jom** [comment]
Job packages comes from WC Paid Listings, which is not this repo, which is why this request is a bit confusing. For enhancement requests for the repository, please submit a support request.

If you'd like a to add an action to WPJM, you can submit a PR request. However, I don't think the action makes sense in `WP_Job_Manager_Email_Notifications`. Seems unrelated. There are already filters in place for controlling the submit job steps (`submit_job_steps`). You might be able to accomplish what you're trying to do by using the `before` callback attribute in the preview step.
