### ISSUE TITLE
"Application email/URL" expects the the URL protocol but is not clear in the error or description

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/WP-Job-Manager#2067]
The "Application email/URL" job submission field expects the protocol (HTTP:// or HTTPS://) when entering a URL. However this is not explicitly stated nor is it clear in the error message when one does not enter the protocol. 

The only error shown is `Application email/URL is a required field`. 

We should make it clearer by using description, placeholder text, and/or error message that the protocol is required.

3415016-zen

**Comment by tripflex** [comment]
So the problem here was actually introduced when the new sanitation methods were added for fields (this previously was not an issue).

There is already handling that would add the `http://` to the value if it was missing, but because this is called AFTER the new sanitation methods are called, it doesn't detect it as a URL so it sanitized through the `sanitize_email` method, causing the value to be blank.

This is the handling that before the sanitation methods would handle this:
https://github.com/Automattic/WP-Job-Manager/blob/a0a769648572e54cc64ed6b95fc466334fb24be7/includes/forms/class-wp-job-manager-form-submit-job.php#L454-L484

Chances are we just need to move this handling to the sanitation methods, as this appears to be a common issue

**Comment by tripflex** [comment]
For anybody that needs to fix this right away, just remove the sanitizer so it uses standard text field sanitizer:

```php
```
add_filter( 'submit_job_form_fields', 'smyles_remove_application_sanitizer' );
function smyles_remove_application_sanitizer( $fields ){
    if( isset( $fields['job']['application']['sanitizer'] ) ){
        unset( $fields['job']['application']['sanitizer'] );
    }
    return $fields;
}
```
```
