### ISSUE TITLE
Ensure _job_expiry is returning in REST API

### ISSUE THREAD

**Issue by cena** [Automattic/WP-Job-Manager#2105]
reported in 3633000-zen.

> In the REST API response for a job listing, I need to see the job's expiry date. It doesn't seem to show under 'meta' currently. I can only see the following fields there: _application, _filled, _featured. How would I add _job_expiry to the API response?

According to Donna in [this convo](https://a8c.slack.com/archives/C6GGX896G/p1610446768376100), "It's configured to be returned in the REST API, but is not for some reason."

**Comment by jom** [comment]
This is intentional. We do show it for authorized users (those who can edit job listings). When we set up the REST API, we tried to not expose additional information to guests that wasn't exposed before. The expiration date was not exposed before, so we are only exposing it to guests now.

They should be able to override this:
```
add_filter(
	'job_manager_job_listing_data_fields',
	function ( $fields ) {
		unset( $fields['_job_expires']['auth_view_callback'] );

		return $fields;
	}
);
```
