### ISSUE TITLE
Submit Job page breaks if user not logged in

### ISSUE THREAD

**Issue by navinp** [Automattic/WP-Job-Manager#2134]
Hello

After adding the short code [submit_job_form] and viewing the page in Incognito mode (not logged in), the page breaks.

https://freelance.sr/test-posting/

Working normally when the user is logged in as employer. 

- WordPress theme: default 2021 theme
- No I did not deactivate ALL plugins to see if the problem has to do with the plugin, I am sure it works fine, when 0,0 other plugins are installed.
- Reproduce: just visit the link above to see how the page breaks.

**WordPress Environment**
- WordPress Version: 5.6
- WP Job Manager Version: 1.34.5
- PHP Version: 7.4.16
- Other important details:

**Comment by jom** [comment]
I'm unable to reproduce the issue locally. Please feel free to re-open if you can reproduce on a fresh install of WPJM.

Two things:
- I think it is a separate plugin issue. It seems to be failing when generating the login form, which some plugins try to override.
- In the browser console, like you have a script error that prevents script loading. It looks like your Google Analytics code has a `<script>` inside of a `<script>`. Not the root cause of this issue, but may cause issues later.

**Comment by demonquark** [comment]
I think this problem occurs with **WP Company Manager**.

Specifically:
``` wp_login_url( add_query_arg( array( 'job_id' => $class->get_job_id() ), get_permalink() ) ) )```

The variable **$class** is NULL.
