### ISSUE TITLE
Can we add job posting location info to the Jobs Dashboard?  A lot of my clients create duplicate jobs and if they want to go back and edit one of the jobs there is no way to know without going into each job listing itself to see what city the jobs are posted in.  Can we add that info to the "info table" on the left side of the job dashboard? It will truly save a lot of aggravation and time.  Ive had a two clients reach out to me on this issue.  Thanks in advance for any help!

### ISSUE THREAD

**Issue by JigJobs** [Automattic/WP-Job-Manager#2203]

**Comment by cena** [comment]
Hi,

Hi @edtaaffe ,

 This area is for bug reports, rather than general support, which is what it sounds like you need.

We support unlicensed users and the free WP Job Manager plugin in our WordPress.org forums, here:

https://wordpress.org/support/plugin/wp-job-manager/

To post there, you'll first need to create an account:

https://login.wordpress.org/register

Cheers,
Cena
