### ISSUE TITLE
I need to integrate it with an ats if thats possible. I was searching the code, but Im not a php guy and its a struggle. I hoped to find where the database updates are done and include an update to the atm database.  Is that possible?  Where is the code that updates new jobs or candidate applications?

### ISSUE THREAD

**Issue by testersoccamp** [Automattic/WP-Job-Manager#2207]

**Comment by testersoccamp** [comment]
I'm not sure what that comment is in aid of.
Ive been upholding the principles of he internet since long before github existed and giving selfllessy of advice where I can.
If you dont want to be helpfull dont get involved, you dont have to.
If you do then use your noggin before your pen.

The question I asked was not a bug question, it was an architectural question.
Your little bug template is useless for that.
Now you've learned something that you dint earn.
There's no charge for that.
This is the internet, in spite of Google, facebook and all the other *****s

**Comment by cena** [comment]
Hi @testersoccamp -

Hi @edtaaffe ,

Thanks for reaching out. This area is for bug reports, rather than general support, which is what it sounds like you need.

We support unlicensed users and the free WP Job Manager plugin in our WordPress.org forums, here:

https://wordpress.org/support/plugin/wp-job-manager/

To post there, you'll first need to create an account:

https://login.wordpress.org/register

Cheers,
Cena
