### ISSUE TITLE
How to see all the mission in [job] with Polylang

### ISSUE THREAD

**Issue by Robertultime** [Automattic/WP-Job-Manager#2209]
I'm currently using Polylang and WP Job Manager at the same time, and I can only see the job of the current language page in [job], and I would like to see all the missions.

For example, if the job page is in English, I can only see the English jobs, when I would like to also see the French one. I've read many topics and tried it, but it didn't solve my problem. Do you have any solution ?

**Comment by cena** [comment]
Hi @Robertultime - 

Hi @edtaaffe ,

Thanks for reaching out. This area is for bug reports, rather than general support, which is what it sounds like you need.

We support unlicensed users and the free WP Job Manager plugin in our WordPress.org forums, here:

https://wordpress.org/support/plugin/wp-job-manager/

To post there, you'll first need to create an account:

https://login.wordpress.org/register

Cheers,
Cena
