### ISSUE TITLE
Not convinced its a bug, maybe I misunderstand

### ISSUE THREAD

**Issue by edtaaffe** [Automattic/WP-Job-Manager#2211]
I am setting up a site for the first time with tis plugin. It looks great and I am looking getting it live. Its my first venture into recruitment.

I want my employers who have submitted jobs or sent them over or told me to get it of their website, to be able to login and make changes.

I want to place that login page and also a register page on the man menu. Just basic good UX
User will visit
Look at main menu first
See login
Login if they are registered
Click register if they are not.
There two use cases for this:
1.  a user discovers the site and wants to register, but may need to get a staff member to upload jobs next week.
2. a jobseeker may want to register and create alerts.

Where I have come to with the install, I can see no way of doing this.
I can create blank pages for login and for register, but there are no pages or shortcuts I'm aware of apart form woocommerce (I dont use woocommerce I will jsut be recruiting)

Can anybody advise on this.
My son would know how to write me some basic php if we need target a particular script or something to login and to register.
Any advice would be great.

Thanks.
E

**Comment by cena** [comment]
Hi @edtaaffe ,

Thanks for reaching out.  This area is for bug reports, rather than general support, which is what it sounds like you need.  

We support unlicensed users and the free WP Job Manager plugin in our WordPress.org forums, here:

https://wordpress.org/support/plugin/wp-job-manager/

To post there, you'll first need to create an account:

https://login.wordpress.org/register

Cheers,
Cena
