### ISSUE TITLE
Jobify theme incompatibility with v 1.36.2 - salary field not showing in job listings

### ISSUE THREAD

**Issue by StefMattana** [Automattic/WP-Job-Manager#2282]
**Describe the bug**
Upon enabling the Salary field, nothing gets displayed in the job listings when running the Jobify theme v 3.11.1 

**To Reproduce**
1. Updated WPJM to 1.36.2
2. Enabled the `Enable Job Salary` option  
3. Posted a new job from the frontend
4. Added a random number in the Salary field
5. Published the post; nothing showed up. 
<img width="1293" alt="Screenshot 2022-06-23 at 17 29 26" src="https://user-images.githubusercontent.com/11662998/175349261-40a4ba92-4156-43a3-84a1-f54545226687.png">
6. Tried to edit the job post from `wp-admin` and saved it again; same result - no salary info published
7. Switching to a default theme solved the issue. 
<img width="644" alt="Screenshot 2022-06-23 at 17 27 12" src="https://user-images.githubusercontent.com/11662998/175349300-a124e682-c87e-46f3-98e9-c8378c742fb2.png">

I have also reported it [here](https://github.com/Automattic/WP-Job-Manager/pull/2263).

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.0
- WP Job Manager Version: 1.36.2

**Comment by aaronfc** [comment]
Hey,
this is because Jobify is overriding the `content-single-job_listing-meta.php` template.
They will need to update the theme to include the new salary field (they can use as reference the updated template):
https://github.com/Automattic/WP-Job-Manager/blob/28d4d1c5dc47ccc05e5ae3182088aae82a018d31/templates/content-single-job_listing-meta.php#L41

As a workaround until the theme is updated one could include the salary at the end of the meta section by using the following snippet:
```
function snippet_append_salary_field_to_listing_meta() {
	?>
	<li class="salary"><?php the_job_salary(); ?> </li>
	<?php	
}
add_action('single_job_listing_meta_end', 'snippet_append_salary_field_to_listing_meta');
```
