### ISSUE TITLE
Job Submission Fields snippet not working on v.1.36.2 

### ISSUE THREAD

**Issue by StefMattana** [Automattic/WP-Job-Manager#2286]
The bug has been reported by a user on this forum thread: https://wordpress.org/support/topic/problem-with-admin-job-submission-form-fields-after-update/#post-15794518

Upon updating the core plugin to v.1.36.2, the script to remove some fields from job submission form in admin (which is based tutorial [here](https://wpjobmanager.com/document/editing-job-submission-fields/)) has stopped working: 

```
add_filter( 'job_manager_job_listing_data_fields', 'custom_job_manager_job_listing_data_fields' );

function custom_job_manager_job_listing_data_fields( $fields ) {

	unset($fields['_company_website']);
	unset($fields['_company_tagline']);
	unset($fields['_company_video']);
	unset($fields['_company_twitter']);
	unset($fields['_company_facebook']);

    return $fields;
```

The script works if rolling the plugin back to previous versions. 

The user came up with a fix that seems to be working: 

```
add_filter( 'job_manager_job_listing_wp_admin_fields', 'custom_job_manager_job_listing_data_fields' );

function custom_job_manager_job_listing_data_fields( $fields ) {

unset($fields['_company_tagline']);
unset($fields['_company_video']);
unset($fields['_company_twitter']);

    return $fields;
}
```  

I'd like to report it here in case you can weigh on it. Thanks!

**Comment by tripflex** [comment]
For some reason they have put all of the fields into that method (when before they were not).

Now/After:
https://github.com/Automattic/WP-Job-Manager/blob/v1.36.2/includes/admin/class-wp-job-manager-writepanels.php#L55-L209

Before:
https://github.com/Automattic/WP-Job-Manager/blob/1.35.3/includes/admin/class-wp-job-manager-writepanels.php#L55-L129

I can't tell why this was done at all since the fields are being pulled from `WP_Job_Manager_Post_Types::get_job_listing_fields();` so not sure why this was changed without any documentation around it (even in commits I can't find any reason this would have been done).

The closest I could find was @onubrooks merging someone else's branch that made this change (https://github.com/Automattic/WP-Job-Manager/commit/7e73bb406e0ab8c9e13101c4e881c4e1754f8fea) but there is no commit message or any details as to why those fields were added to this method now, which is what is causing the issues (and who knows what other ones now too)

**Comment by Gnodesign** [comment]
This has been done to add the `_remote_position` and `_job_salary` field to the writepanels but it has not been implemented correctly. The field should have been added in the `WP_Job_Manager_Post_Types::get_job_listing_fields();` function where all fields get pulled from: https://github.com/Automattic/WP-Job-Manager/blob/28d4d1c5dc47ccc05e5ae3182088aae82a018d31/includes/class-wp-job-manager-post-types.php#L1496-L1590

Right now the `_remote_position` and  `_job_salary` aren't being registered as a meta which means you can't show them via REST API either.

**Comment by onubrooks** [comment]
PR [here](https://github.com/Automattic/WP-Job-Manager/pull/2288) @tripflex @Gnodesign @StefMattana 

@fjorgemota any chance you could add this to the next release?
