### ISSUE TITLE
Job Manager Application , Get Error 503 after apply job button clicking 

### ISSUE THREAD

**Issue by PadPadri** [Automattic/WP-Job-Manager#2303]
**Describe the bug**
When I submit a job application throught the application form, I get a 503 error.(Error 503 backend fetch failed”)
When I check the logs I see the following error : 
ncaught Error: Call to undefined function get_the_job_reference() in /home/oselitz/www/wp-content/plugins/wp-job-manager-applications/includes/wp-job-manager-applications-functions.php:438
It's maybe due to the last update I've done.

**To Reproduce**
1. Go to a job annoncement
2. Click on apply job
3. fill the datas'
4. Submit
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/110182575/181563405-846a8247-ab2d-4b43-967d-87f1c246d772.png)

**WordPress Environment**
- WordPress Version: 6.0.1
- WP Job Manager application Version:  2.5.4
- Other important details:

**Comment by alexsanford** [comment]
Thanks for the report! I just gave this a try using the latest version of WP Job Manager (1.37.0) and Applications (2.5.4) and submitting an application seemed to work fine for me.

The error message refers to an undefined function `get_the_job_reference`. I looked through the codebase and I don't see any reference to a function with that name, even on the line of code that your error message points to. Are you using any third-party plugins that may be integrating with the Applications? Or do you have any customizations that you've added yourself?

I'm going to close this issue as it is not reproducible on our end, but I would suggest getting in touch with support through your wpjobmanager.com account. They can walk you through some debugging steps to see where this issue is coming from.
