### ISSUE TITLE
Apply with linked In not working

### ISSUE THREAD

**Issue by CarlosLopezRoa** [Automattic/WP-Job-Manager#255]
I have followed the instructions in the documentation and provided the API keys in the config but when i click the button "Import from LinkedIn" nothing happens, not a sigle API call. The API requests in developer.linkedin.com is empty. This is independent of the browser and the linkedin session.

**Comment by harishagrawala** [comment]
"In order to use this feature you need to go to Resumes > Settings > Resume Submission and enable the LinkedIn Import option, then enter your LinkedIn API key from your LinkedIn application." below mathod we are following but there is no moment after click the button, is we can remove the API and blank the field under Resume Submission section, button is working and re-direct the link https://www.linkedin.com/uas/oauth2/authorize?original_referer=http%3A%2F%2Fwww.mydomain.com%2Fsubmit-resume%2F&token=&isFramed=false&lang=en_US&immediate=true&client_id=&type=user-agent&_ts=1464634992700.846&xd_origin_host=http%3A%2F%2Fwww.mydomain.com
