### ISSUE TITLE
Enabling the checkbox for job alerts in the backend (to allow receiving emails) breaks the alerts form in the user frontend

### ISSUE THREAD

**Issue by promptpress** [Automattic/WP-Job-Manager#2578]
Bug:

When the checkbox for job alerts in the backend (to allow receiving emails) is activated, you get the following behaviour:

1. in job alerts on the user frontend when you enter nothing and try to save, nothing happens, especially there is no error message and the user does not know, what’s going on
2. same when you do enter alert criteria and don’t check the checkbox (in the alerts frontend form) → no error message, as otherwise usual

To Reproduce:

Switch the checkbox in the backend on/off and test the alerts frontend form. If the backend checkbox is switched off, all is fine again → 1. works as expected and the user gets an error message

Expected behavior:

Alerts frotend form has no issues depending on the checkbox-setting.

- WP 6.3.1
- Latest public release of of the WPJM package as of now
- Cariera theme latest version as of now
- PHP 8

**Comment by gikaragia** [comment]
Hello @promptpress,

I have tried the steps you suggested and a popup currently exists that explains to the user to check the checkbox in order to proceed. 

<img width="485" alt="Screenshot 2023-10-25 at 11 34 55" src="https://github.com/Automattic/WP-Job-Manager/assets/53191348/4af4cb7b-6975-4e72-b1c3-b4c9311f093e">

This seems like a conflict with your theme or your local installation. If you have purchased Alerts from [our website](https://wpjobmanager.com) and you have an active license, I would suggest to request support by following the appropriate link in [our support page](https://wpjobmanager.com/support/).
