### ISSUE TITLE
Job Applicaton-Field type "select" does not take values using pipe (|) to seperate the values

### ISSUE THREAD

**Issue by hadiheidari64** [Automattic/WP-Job-Manager#2786]
I am using Job applications Module and created my form, The text field works fine as expected but when I choose Field type 'select' or 'multiselect' to put different values, I should be able to put different values and seperate them using Pipe(|), I can input the values but when I update or save the form, it does not take it and when I go to the form page it soes not show up there

To replicate the issue:
go to: Job Applications plugin
go to : Application Forms and Add new
add a field and put the type 'select' or 'Multiselect'
now put more than one value in placeholder/options and separate them using pipe (|)
Save the form as draft or publish it, go back to the fields, and you will see that the option field is empty.

Any idea how to resolve the issue or it is a bug
![pipe issue](https://github.com/Automattic/WP-Job-Manager/assets/91212532/b24d732d-8fe1-4108-a1d3-fbdad2c52993)

**Comment by schroeder-hesel** [comment]
I just bought the extension today and sadly got the same error. I hope this is getting fixed soon.

**Comment by hadiheidari64** [comment]
Is there any update, or does anybody know how to resolve it?

**Comment by gikaragia** [comment]
Hello! Thank you for reporting this. We have implemented a fix for which is going to be included in the next release. Until then, you can replace the `html-form-field-editor-row.php` file the applications plugin with the file attached. I compressed it since GitHub doesn't allow attaching of PHP files.

[html-form-field-editor-row.php.zip](https://github.com/Automattic/WP-Job-Manager/files/14886880/html-form-field-editor-row.php.zip)
