### ISSUE TITLE
Accessibility issues. 

### ISSUE THREAD

**Issue by adamjohndaly** [Automattic/WP-Job-Manager#2823]
**Describe the bug**

> We noticed two accessibility issues that we wanted to report for a future fix. Screenshots below.
> 
> A – Form field missing a label
> ARIA – ARIA attribute unsupported or prohibited

Deactivated all plugins on site to troubleshoot. Results are the same. 

**To Reproduce**

**Screenshots**
![A-Form-field-missing-a-label](https://github.com/Automattic/WP-Job-Manager/assets/18173779/ed898177-4b9e-4105-888f-9908d9f7a68b)
![ARIA-aria-label-on-div](https://github.com/Automattic/WP-Job-Manager/assets/18173779/c20eaae5-9815-44d2-8cc0-3ca43f761ac3)

**Expected behavior**
A form to have a label
ARIA attribute to be supported. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

- WordPress v6.5.3
- Twenty Twenty-Four v1.1
- WP Job Manager v2.3.0

**Comment by mikeyarce** [comment]
For the first issue - I think that's a problem with the Select2 library - but it does look like the select has a label - maybe because there are 2 selects in the same place the scanner is not seeing it properly?

For the second issue - I'm not sure why using `<div class="jm-dashboard-job-column job_title" aria-label="Title">` is not supported?  I feel like it adds good context for that `div` but happy to take suggestions. 

Going to close this for now as I don't think it's actionable, but if someone has some suggestions for how to address this, feel free to comment!
