### ISSUE TITLE
Unattach files when a new attachment is uploaded

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#510]
To repro:

1. Create a job listing with a company logo.
2. In the Media Library, observe the logo attached to the job listing post.
3. In the Job Dashboard, edit the job, upload a new logo, and submit it.
4. Job listing shows a new logo on Jobs page.
5. In Media Library, both the old and new files are attached to the job listing.

Ideally only the latest file to be attached to the listing would show as attached in the Media Library. This would provide compatibility with plugins that, for example, clean out files that are no longer in use from your Media Library.

Came up in Help Scout ticket 6880.

**Comment by blue928** [comment]
Not sure if this should be a separate issue, but I have an extension of this idea that I've been creating a custom solution for.

I've added 'ajax' => 'true', 'multiple' => 'true' to the file (Logo) field allowing people to upload multiple images to a post. This works great!

But, when you remove an attachment via the [remove] link, the files are still there on the server. Since a user doesn't have access to the media library to select files for use in a future post then, in my opinion, having a way to manage them would be greatly beneficial.

1) If someone clicks the 'remove' link, then the item is not just unattached, but deleted.
2) After an ad expires it's "automatically deleted after 30 days." Should that happen, or it's manually deleted, unattach and remove files from the server
3) Perhaps a setting (option) that allows either of the two functionalities? I can see where a company using this for their own internal purposes may be accessing the files from the media library and thus would access to them regularly.

**Comment by mikejolley** [comment]
Not sure on the best way to handle this yet; we store image URLs not attachment IDs making this one tricky.

**Comment by kraftbj** [comment]
Perhaps something like Pippin put together: https://pippinsplugins.com/retrieve-attachment-id-from-image-url/

**Comment by spencerfinnell** [comment]
Check out https://developer.wordpress.org/reference/functions/attachment_url_to_postid/ too. We use that in Listify now instead the other method.

**Comment by kraftbj** [comment]
Wrong order of search words on Google it seems. Awesome.
