### ISSUE TITLE
Few questions/possible issues with WP Job/Resume manager plugins

### ISSUE THREAD

**Issue by hughesitconsulting** [Automattic/WP-Job-Manager#607]
•Neither the Job Manager or resume manager seem to provide the ability to turn on CAPTCHA.  Will this be added to a future release?
•I unblocked both the Job Dashboard & Candidate Dashboard (i.e., turned off the settings to require a login). However, both are still requiring a login.  Is this a known bug?
•It doesn't appear that we have the ability to disable the logo upload on the "Post a Job" page under Job manager. Is there a way we can turn this off?

**Comment by tripflex** [comment]
1.) There isn't anything built in for doing this and enabling it, but there is a tutorial already on wpjobmanager.com for how to add recaptcha.  I don't know if it will ever be added to core or not (but it is a feature in my field editor plugin):
https://wpjobmanager.com/document/tutorial-adding-recaptcha-job-submission-form/

2.) No this is not a bug, you must have a login in order to be able to use the dashboard as each listing will be associated with a user ID.  If the listing is posted by someone not logged in, it will be associated with "Guest User" .... allowing someone who is not logged in to use the dashboard means they would have access to any guest posted listings.  So in simple terms, if you want to use dashboards and allow users to edit listings, they must have an account, otherwise there is no way to associate and verify who the listing belongs to.

3.) There is nothing built-in for this, but again there is documentation on how to do this on the wpjobmanager.com website (or using my field editor plugin).  You would just use unset to remove that field from the array:
https://wpjobmanager.com/document/editing-job-submission-fields/

```php
unset( $fields['company']['company_logo'] );
```
