### ISSUE TITLE
Read more stuff from query string

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#610]
As seen here:

https://github.com/Automattic/WP-Job-Manager/blob/1.24.0/includes/class-wp-job-manager-shortcodes.php#L241-L250

... we only read the keywords, location, and category from the query string. Maybe we should read more, e.g. salary info if someone's added it? Not sure what determines what WPJM should read and what it shouldn't.

From: https://wordpress.org/support/topic/adding-salary-field-to-custom-search

**Comment by kochhase** [comment]
hi mike,
will this will help us for the future? facetwp has the integration of WPJM on the roadmap. Maybe Matt Gibbs need some help for that.
https://workflowy.com/s/bb298527-78f6-3456-d050-2ce74e9c19a1
regards

**Comment by mikejolley** [comment]
This won't be needed. If you're adding a custom field, such as salary, you're also going to be passing that value to WPJM via a field of some sort. In your code which outputs the field, you could easily add a check for $_GET.

Doing this at WPJM level is no good because you a) don't know the field names and b) have no where to send the value (because its handled elsewhere).

Hope makes sense :)
