### ISSUE TITLE
Add "View" button for attachments in backend

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#631]
Would be nice to have a button that just opens the attachment in a new tab. Like so:

![screen shot 2016-03-09 at 2 05 11 pm](https://cloud.githubusercontent.com/assets/5512652/13646984/f753ca9a-e5ff-11e5-888d-1b7949bb4e19.png)

From #2568879-t.

**Comment by mikejolley** [comment]
@aheckler not really ideal since:

1. This is an edit interface. The value would be changed and thus view link would not be 'current'
2. Multiple attachments are supported in some cases
3. It depends if the URL entered is relative or absolute which would make linking more difficult.

Links should be displayed when 'viewing' applications only IMO - thats in the list table and on the frontend views for employers.
