### ISSUE TITLE
License notifications don't link to plugins page

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#638]
#### What I Expected To Happen

When viewing the Dashboard, the notifications that tell me to enter license keys for my add-ons should link to the relevant section of the plugins page.
#### What Happened Instead

The links only contain the anchor, not the plugin page itself, so unless you're already on the plugin page, they don't go anywhere. Also the notification says "in the plugin list below", which only applies if you are already on the plugins page.
#### Steps to Reproduce the Bug
- Install and activate an add-on.
- Go to Dashboard.
- Click the "Please enter your license key" link.
- Watch in dismay as nothing happens.

![image](https://cloud.githubusercontent.com/assets/1990037/13985832/df34561c-f0f6-11e5-88f0-879ac44b95c6.png)

**Comment by jom** [comment]
This code exists in all of our paid WPJM plugins and isn't in WPJM core. There is also some awkwardness when applying a license key (you need to check at least plugin in the plugin manager before submitting form). Should we keep this license management code in each individual plugin or would it be worth investigating moving some/all of it into WPJM core? @kraftbj @dbtlr @pgk

**Comment by kraftbj** [comment]
I like the idea of having a central updater, but I think it may be against the plugin repo rules to have the actual upgrader in Core (since it downloads updates from WPJM's site). The licensing code itself likely can be abstracted out.

**Comment by jom** [comment]
I was just thinking the license code, not having a central updater.

**Comment by spencerfinnell** [comment]
The actual license management and what not can be in the core plugin but configuring it to make the requests to wpjobmanager.com would need to be done in the premium extension separately (as far as I am aware).

**Comment by dbtlr** [comment]
This is a tricky one. On one level, this exact issue is because a global license key is missing. However, since not all plugins are bundled under a single license, or at least don't have to be, it makes it hard to say this code should be centralized.

Perhaps a central alert function would be appropriate. However, I'd need to dig in and see what level of duplication we're really talking about.

I'm open to see a PR of what you suggest @jom. However, I wouldn't get too caught up in the greater meta nature of this problem if there is a simpler answer to this issue.

**Comment by jom** [comment]
Agreed. It would also be something we'd probably need to phase in. I'll start working on fixing the main issues for now. If I see an obvious way to phase in something that will reduce the duplication of code I'll put together a PR.

**Comment by jom** [comment]
All merged!
