### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by rahulatoz** [Automattic/WP-Job-Manager#644]
hello Friends,
when i am using application plugin with wp job manager its working well
BUT when i apply on particular job with uploaded resume its give me 
--------------------------------
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator to inform of the time the error occurred and of anything you might have done that may have caused the error.

More information about this error may be available in the server error log.
--------------------------------------------
Please could you suggest me why i am getting this error?

**Comment by tripflex** [comment]
As the error message states, more information about this error may be available in server error log .... did you not check this?  It's impossible for us to know what the problem is without the error log as it's probably not a bug, but a compatibility issue or server issue.

https://codex.wordpress.org/Debugging_in_WordPress

Set `WP_DEBUG` to TRUE, `WP_DEBUG_LOG` to true, go back to your site and cause the error to happen again, then go to your `wp-content` directory and there should be a `debug.log` file that should have the error in it

**Comment by kraftbj** [comment]
Having not heard back, going to close this. Happy to reopen with additional details.

**Comment by tonyhammarlund** [comment]
I have the same issue. The file path for the attachment is http://lastat.staging.wpengine.com/wp-content/uploads/job_applications/5c346b2659f88/INV01504295.pdf

But when checking in the uploads folder there are no job_applications folder.
