### ISSUE TITLE
There no phone number in default fields when posting a resume?

### ISSUE THREAD

**Issue by stefek99** [Automattic/WP-Job-Manager#646]
I've purchased theme from ThemeForest.

I've purchased extra plugins.

Imported sample content.

Current state:
![image](https://cloud.githubusercontent.com/assets/249703/14225836/624b50d2-f8d1-11e5-8232-7514a094333e.png)

I do not understand the following items:
* Why there is no phone number?
* Why there is photo upload? (in some countries it's a big no-no)
* Why I have to enable resume upload in options, it should be by default too.

I can customise the fields myself - https://wpjobmanager.com/document/resume-manager-editing-submission-fields/ - I just don't understand why not stick to smart defaults?

**Comment by tripflex** [comment]
They are just default basic fields added, and the resume upload has to be enabled because that allows someone to upload a file to your server ... that's a lot different than someone just saving a text value of a field, because you allow them to upload a FILE

Photo upload field because almost all resume software or similar allows for some type of candidate photo, whether that's a no-no in some countries, it's used in more countries than not.

The same could be said about having a phone number field, in some countries that's a no-no asking people to give you their phone number, in some it may not.

There's numerous sides to why or why not fields should or shouldn't be default, but that's also why it's very easy to remove or add any you want.
