### ISSUE TITLE
Add a shortcode for search form

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#694]
It would be a really nice enhancement to have a shortcode that includes just the search form without any job listings.

Requested in 2703001-t

**Comment by volodymyrpekh** [comment]
This sounds like a pretty useful and smart thing to do. +1 vote!

**Comment by davoraltman** [comment]
Workaround and a solution for this - https://wpjobmanager.com/document/tutorial-creating-custom-job-search-form/

**Comment by code23-isaac** [comment]
> Workaround and a solution for this - https://wpjobmanager.com/document/tutorial-creating-custom-job-search-form/

link 404s :(

**Comment by code23-isaac** [comment]
Was this ever implemented?

**Comment by richardmtl** [comment]
@code23-isaac We recently unpublished that document because the tutorial no longer works. We need to make some changes to the plugin for it to work again. I do not have a timeline for when we'll  get to that, sorry!

**Comment by code23-isaac** [comment]
@richardmtl thanks for the reply – what would be involved in achieving this? Need it for a current project

**Comment by richardmtl** [comment]
@code23-isaac the relevant issue is https://github.com/Automattic/WP-Job-Manager/issues/1804

**Comment by code23-isaac** [comment]
We have got this to work by clearing the sessionStorage cache on form submit:

```
  $("#search_form").on("submit", function() {
    sessionStorage.clear();
  });
```

**Comment by KZeni** [comment]
Okay, should this issue be reopened since the article with the workaround is no longer available, and there's a problem experienced even when using the unpublished workaround as mentioned via https://github.com/Automattic/WP-Job-Manager/issues/1804 from 8 days ago...?

I'm thinking this issue is valid (open) until the problem with the workaround is fixed & released and the workaround has been re-published.
