### ISSUE TITLE
Set Company Logo Translation Bug with WPML

### ISSUE THREAD

**Issue by xgougeon** [Automattic/WP-Job-Manager#759]
I want company logo to be also copied when I duplicate a job in order to translate it to another language

Instead, company logo is set to blank

To reproduce the bug:
- have both wp-job-manager and wpml activated
- create a job in language 1
- click on "translate to language" and tick "duplicate" in post's wpml translation panel
- this will generate a duplicate translation of the job in language 2 but company logo is set to blank

**Comment by spencerfinnell** [comment]
Do you have post meta set to sync in WPML settings?

**Comment by vukvukovich** [comment]
@xgougeon I've tried to replicate issue but for me duplication is working normally.

**Comment by davoraltman** [comment]
Can't reproduce this either. Works as intended.

**Comment by vukvukovich** [comment]
@xgougeon 

You are experiencing this because of **WPML Media Translation** plugin.
You need to set it up first by going to **WPML >  Media Translation** and clicking on the button **"Start"**.

This way, all your media files already uploaded will become multilingual, and if you duplicate any Job afterwards it will duplicate logo as well.

Warm regards
