### ISSUE TITLE
job category page not showing

### ISSUE THREAD

**Issue by diptisombanshi** [Automattic/WP-Job-Manager#760]
I have created categories for job listing and I want to show particular job category on each page but i get (?taxonomy=job_listing_category&term=admit-card) this which listed all categories.

**Comment by edd677** [comment]
@diptisombanshi we have implemented this successfully. Simply create new pages in WordPress and add the shortcode: [jobs categories=nameofjobcategory]

This will only show jobs from that category, and the category filter is hidden. Works v effectively.

**Comment by kraftbj** [comment]
We should set the expectation better. There's rewrite code so on would expect example.com/job-category/slug/ to work, but it seems not to at the moment.

**Comment by spencerfinnell** [comment]
The rewrite code is only generated on themes that define support for WP Job Manager, and it is up to the theme to create taxonomy archive templates for this. 

https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-post-types.php#L72

Otherwise you can use the shortcode as mentioned above.
