### ISSUE TITLE
Multilangual site (WPML) - Setting Pages only one page for all languages can be set

### ISSUE THREAD

**Issue by Lens40** [Automattic/WP-Job-Manager#786]
#### What I Expected To Happen

When I set up WP Job Manager I expect to be able to set the pages in the settings for each language.
![set_page](https://cloud.githubusercontent.com/assets/19168364/19446221/1482b2d8-9498-11e6-8a79-9ccb887092e2.PNG)
#### What Happened Instead

Unfortunately I can only set one page for all languages which breaks some functionalities in the languages that couldn't be set which rely on these settings.

Currently I have to decide for which language I want to do these settings as it can only be done for one.
#### Steps to Reproduce the Bug

WP Job Manager + WPML

**Comment by spencerfinnell** [comment]
There is Polylang support for this already: https://github.com/Automattic/WP-Job-Manager/blob/53efe87050c205984d6e7b96e09ef9b015590a64/wp-job-manager-functions.php#L635

WPML support would require https://wpml.org/wpml-hook/wpml_object_id/

**Comment by spencerfinnell** [comment]
@donnchawp I think this would be worth adding. Would fix a good chunk of WPML issues.

**Comment by donnchawp** [comment]
That "page settings" page only creates a new page with a shortcode in it. It doesn't do anything special to them, other than that.

I installed WPML this morning and added the wpml_object_id filter as @spencerfinnell suggested and it looks like I was able to create landing pages for different languages through the standard page editor interface.
WPML lets you create other language versions of any page so I created French and Italian (I had those .mo files for the plugin downloaded already) "versions" of my jobs listings page on my test server.
Both pages only have the "jobs" and "submit_job_form" shortcodes but when I viewed them the pages were mostly translated!
The URLs looked like this too:
http://local.wordpress.dev/it/jobs-list/
http://local.wordpress.dev/fr/french-jobs-list/
The permalink to each page can be different strings because they're completely different pages to the English page.

Unfortunately the jobs types list wasn't translated but we're getting somewhere.

![screen shot 2016-10-18 at 13 11 01](https://cloud.githubusercontent.com/assets/5656673/19477403/dcc66a26-9535-11e6-803f-980feab3f79a.png)

![screen shot 2016-10-18 at 13 09 08](https://cloud.githubusercontent.com/assets/5656673/19477447/102b1d6c-9536-11e6-816e-2db9bca4fc02.png)

![screen shot 2016-10-18 at 13 09 32](https://cloud.githubusercontent.com/assets/5656673/19477456/16c9c84e-9536-11e6-8ca6-f2619df69350.png)

**Comment by donnchawp** [comment]
Unfortunately the jobs on the jobs list link to /jobs/test2/ etc, not /fr/jobs/test2/ :(

**Comment by vukvukovich** [comment]
Hi,

I think this is not an actual issue, page IDs can be translated through wpml-config.xml file.
Have you tried that?

Warm regards

**Comment by spencerfinnell** [comment]
@donnchawp If the returned jobs are in English (they look like they are) then the permalinks should link to the English listing as well. 

I'm not sure WPML's default behavior on returning untranslated results is though. For Poylang if your current site language is French and you have English (default language) listings that aren't translated those will not be used as fallback when viewing in French. In my opinion this is the correct behavior.

**Comment by donnchawp** [comment]
@vukvukovich - the issue reported is that WPJM doesn't allow you to create language specific pages but since the OP is using WPML there is a mechanism to do that. I'm a noob at using WPML, this is my first time trying it, so I did not know you could edit an xml file.

@spencerfinnell - interesting observation and you're right. I wonder how do sites handle job descriptions written in different languages? Maybe a taxonomy?

**Comment by Lens40** [comment]
@donnchawp the issue is not that you can not create pages in many languages with the short codes, the issue is that some plugins and widget rely on the configured page for redirects and linking. In our case its the jobify theme which relies on it for the pricing table to send the user directly to the create a job page. So if you have set the english job listing page, then the german pricing table will also link to that english one instead of the german one. Also the Jobify-Stats-Plugin  relies on that setting to work correctly.

**Comment by spencerfinnell** [comment]
@Lens40 That will all be fixed when the filter is added to the `job_manager_get_page_id()` function, which our themes and plugins use. This will allow WPML to interject and pick the properly translated page. 

@donnchawp You should just need to translate the job listing like you did those pages: https://wpml.org/faq/how-to-translate-custom-types/ -- ensure it's set to be translatable and you can translate it. Then the current WPML shims in the plugin should return those results: 

https://github.com/Automattic/WP-Job-Manager/blob/1fa53adb5ce9b5bfea3b0700e87697897fe018cc/wp-job-manager.php#L122
https://github.com/Automattic/WP-Job-Manager/blob/53efe87050c205984d6e7b96e09ef9b015590a64/wp-job-manager-functions.php#L48

The real issue comes with submission. The submission form needs to send the current site language. Polylang looks for a `$_POST` var on the `save_post` action: https://github.com/polylang/polylang/blob/ba967560a3d22a5659acdf0839005084e6473339/admin/admin-filters-post.php#L500 which would be easy to set. 

I can only assume it's not that easy for WPML.

**Comment by Lens40** [comment]
@spencerfinnell @donnchawp for WPML you can have to behviours if I am not wrong:

First - display all jobs of all languages on all language versions. In this case when you are on the german version and you open an english job you are redirected to the english version. So depending of the language of your job the website language will change. 

Second - Display only the jobs of the language you are in.

What we do is: When we create jobs we are duplicating all jobs into all languages so you still can see all jobs from all over the world without switching your site language and by that we are also adding the right hrfelang-tags to avoid duplicate content.

**Comment by Lens40** [comment]
For the front end submission page, depending on which language you are currently using the job will be normally created in that language of the user. From my experience 99,99% of the jobs are not translated...

**Comment by Lens40** [comment]
@donnchawp I guess that also the job duplication feature of wp job manager relies on those settings. At least it does not work on my website.

**Comment by donnchawp** [comment]
In #787 I added the filter but I'm not sure if it helped or not.

I told WPML to allow the custom types to be translated, and the job listing page got all the nice + links. I created a French translation for one of my jobs, but the "/fr/poste/french-test2/" URL still returned a 404, and the job types and categories metaboxes are blank in the job editor. Needs more work to figure this out.

**Comment by donnchawp** [comment]
With WPML installed the types editor allows you to enter translated versions of that taxonomy. Those translated types show in the job editor for that language.

**Comment by donnchawp** [comment]
@spencerfinnell - good news. The frontend submission page when viewed on a translated page creates jobs for that language in my testing.

**Comment by donnchawp** [comment]
@spencerfinnell, @Lens40 - can you test this branch on a test server? https://github.com/Automattic/WP-Job-Manager/tree/786_wpml_translation_support 

It has the wpml_object_id filter added.

**Comment by Lens40** [comment]
Hi @donnchawp I requested my developer to do a test on our test machine. I'll update you once it has been done. Thanks!

**Comment by donnchawp** [comment]
Any luck with testing this? I want to get a new release out soon and this and the other wpml issue are holding it up.

**Comment by Lens40** [comment]
I just added the new code snippet to my current install on a dev server. So far I could not figure out what it does. The WP Job Manager -> Settings -> Pages has not changed (no options to set different pages for different languages) and I have not found any additional setting option in WPML for that. Can you tell me where I should expect to be able to set the pages? Thanks

**Comment by donnchawp** [comment]
It doesn't add new pages because the plugin itself doesn't support more than one language and likely never will. I presumed that WPML would intercept the calls to get the various pages when called from pages containing different languages. 

I'll have to debug that part of it a bit more.

**Comment by donnchawp** [comment]
@Lens40 - with WPML installed did you create translated copies of the WPJM pages from /wp-admin/edit.php?post_type=page ?
The job_manager_get_page_id() function in WPJM should return the correct page as long as the language is set correctly. job_manager_get_permalink() uses that get_page_id() function so that should return the right URL too.

**Comment by designlab9898** [comment]
What happens if there is only one job limit and if a person adds a job
listing on Language French and then adds a different job listing on
Language English? Does this job listing will auto duplicated into the
English Language for more convenience when editing into a different
language?

**Comment by Lens40** [comment]
@donnchawp ok I understand the intended behaviour but I can't give you a positiv feedback. Example: I use @spencerfinnell Stats-plugin which generates a "Stats-link" in the job management interface. I created the "Stats-Page" and translated it into the different languages. Then i have set the configuration in WP Job Manager -> Settings -> Pages  to use the "Stats-Page" for the stats Dashboard. 

What happens: When I am on the english website and I hit the "Stats-Link" i am redirected to the english dashboard (ok fine - i set the page via the "english" backend so thats the normal behaviour). When I am on the german or french website I am still redirected to the english dasboard. So in that case the translations are not taken into consideration. 

![stats](https://cloud.githubusercontent.com/assets/19168364/19701469/d5808a78-9afb-11e6-8a46-ea6d4348eee9.PNG)

**Comment by Lens40** [comment]
@donnchawp  some positive.... the duplicate a job function does now work so maybe afertall there is an additional bug with Stats Dashboard. I'll test the other pages to see.

**Comment by Lens40** [comment]
@spencerfinnell can you test the modification with your stats plugin and the pricing widget of jobify. My developper made a work around but I can't find where he did the changes.

**Comment by Lens40** [comment]
@vukvukovich the main issue is/was that in WPJM settings you have to choose for certain functionalities the page where the related short code is inserted. E.g. for the stats plugin from astoundify you need to select the page where the short code is inserted to work correctly (see first screen shoot). 

When you use WPML the issue is that it does not take these settings over to the other languages of the same page. E.g. when you switch the admin language I would expect to see the same selected page but from the other language version (the linked version). Instead you see "no pages". See following screen shoots.  

![ds_en](https://cloud.githubusercontent.com/assets/19168364/25491788/44aa2b38-2b71-11e7-827d-dd4c147c2d7d.PNG)
![ds_fr](https://cloud.githubusercontent.com/assets/19168364/25491793/45766a9a-2b71-11e7-8c35-abc633fe8103.PNG)

So for add-ons that need this page value to work it will only work on the one page in that one language you have selected. In the other language version it will not work as expected e.g. redirect you the language version of the page you have set in WPJM-Settings. Hope that helps you to understand that issue.

**Comment by vukvukovich** [comment]
@Lens40 Can you tell me which add-on since I want to commit fix for this issue and I don't have "stats dashboard" page.

**Comment by Lens40** [comment]
In our case it was this Plugin: https://astoundify.com/products/wp-job-manager-stats/
Adding the Dashboard page. The other pages are the standard pages of WPJM

**Comment by jom** [comment]
Closing this for now. This should be fixed for WPJM's core pages. We've added a filter that should help WPJM plugins support both Polylang and WPML page ID translations: [wpjm_page_id](https://github.com/Automattic/WP-Job-Manager/blob/ed591b28f0ab75bb1bbc8af11e554b5a7c268baa/wp-job-manager-functions.php#L721)

**Comment by vukvukovich** [comment]
I've installed Stats add-on and shortcode is working on all languages in front-end @Lens40.

**Comment by Lens40** [comment]
Great !

**Comment by vukvukovich** [comment]
@Lens40 Automatic page translation fix proposed here: https://github.com/Astoundify/wp-job-manager-stats/pull/79 

Cheers!
