### ISSUE TITLE
Add Integration with Formidable Forms

### ISSUE THREAD

**Issue by surfjam** [Automattic/WP-Job-Manager#802]
Would it be possible to add Formidable Forms as a form integration? FF has well over 100,000 installs, it's well documented and their devs are willing to be helpful.

**Comment by tripflex** [comment]
I mean it may be possible, but wouldn't be something that easy to do, mainly due to the way that the fields are handled. The forms also integrate with the resumes plugin for field handling, and the fields are stored in arrays different on the frontend and backend.  Then you also have the template files which handle each field type, the field outputs, as well as backend validation.

Only reason I say this, is because when I first found this plugin that's what I tried to do ... was to integrate it with other form plugins (ones that are 2-3 times more popular than FF) ... and ended up having to build my own, hence the birth of the WP Job Manager Field Editor.  I would have much rather built an addon plugin for another form plugin, than building one from scratch, but that ended up in a lot of wasted time I wish I had started from scratch to begin with.

To answer your question in regards to the core plugin, I doubt that will happen because that would mean a ton of work for the core developers, almost having to completely refactor form handling, which would then break compatibility with their existing addons, and other themes and plugins that are already integrated with the way fields currently work.  A lot of themes and other plugins rely on the existing field handling methods for a lot of the features that they provide.

Maybe @kraftbj or one of the other core devs can weigh in on this, but that's my opinion from the past 2+ yrs experience in dealing with WPJM

**Comment by spencerfinnell** [comment]
Closing since I've only seen 1-2 requests for over the years. A custom solution would be possible but is not currently requested enough.

**Comment by seyedahmadqolamy** [comment]
im sorry but i dont found my answer about using gravity forms instead of default submit form in wp job manager. i made a form by gravity forms and now i want to use it for submitting form in wp job manager, how? this is question : is there way for begginers to use gravity forms and wp job manager togethere.

**Comment by tripflex** [comment]
@seyedahmadqolamy unfortunately no there isn't any easy way to do this, you would need to write your own custom code to handle all the values submitted via the form, and then create the listing, as well as updating the listing when it's edited ... and at that point you might as well just code a new plugin forking this one.

Here's some documentation on editing the fields with PHP:
https://wpjobmanager.com/document/editing-job-submission-fields/

Here's the filter used for the fields (on frontend):
https://github.com/Automattic/WP-Job-Manager/blob/master/includes/forms/class-wp-job-manager-form-submit-job.php#L153
