### ISSUE TITLE
WP Resume Manager

### ISSUE THREAD

**Issue by rahulpokharkar** [Automattic/WP-Job-Manager#811]
Linkedin import for resume doesn't work, even after using Client Id from  app created in Linkedin

**Comment by franksinatrany** [comment]
the same...

**Comment by kraftbj** [comment]
LinkedIn requires very exact permissions and you need to apply to their advanced programs now. https://developer.linkedin.com/partner-programs

http://thenextweb.com/dd/2015/02/12/linkedin-takes-aim-developers-plans-lock-apis/

We discontinued our Apply with LinkedIn add-on for this reason. We've left the setting in Resume Manager for those users who joined the API before the restrictions, but will continue to consider removing it for folks who are not using it due to this.
