### ISSUE TITLE
Listing Expiry Date 1 day earlier than Expiration Date

### ISSUE THREAD

**Issue by cena** [Automattic/WP-Job-Manager#822]
#### What I Expected To Happen

Viewing the expiration date on a job listing would appear the same in both the dashboard and on the job editing page.

[screenshot](https://cloudup.com/cTBAdfmvimX)

#### What Happened Instead

Expiration date on job editing page shows expiry 1 day earlier than shown in dashboard  of site.

[screenshot](https://cloudup.com/cNp4YC2g27r)

#### Steps to Reproduce the Bug

In Listings, edit any listing with an expiration date and view 'Listing Expiry Date'.  Changing the date and clicking save reverts to the original (1 day earlier) date in the Listing Expiry Date field.

Possibly related: [#805](https://github.com/Automattic/WP-Job-Manager/issues/805)

Also see from 9 months ago: [Listing Expiry Date isn't working correctly](https://wordpress.org/support/topic/listing-expiry-date-isnt-working-correctly/)

**Comment by rachelsquirrel** [comment]
Another report in #2939959-t

**Comment by JediMoff** [comment]
This is what I ended up doing to fix the issue on the front end

edited this file

/wp-content/plugins/wp-application-deadline/assets/js/deadline.js

Changed line 17 from

var date = new Date( jQuery(this).val() );

to

var date = new Date( jQuery(this).val().replace(/-/g, ‘\/’).replace(/T.+/, ”));

Question is there a way for me to do this in a function or child theme override?

Thanks
J

**Comment by celiageeks** [comment]
Same problem here, started noticing about a month or two ago.  I hope a fix for this issue comes up soon or a way to fix it.

**Comment by approots** [comment]
Same problem. It has to do with setting the jQuery datepicker explicitly and incorrectly with this date format: yyy-mm-dd. For example, JavaScript new Date('2017-01-27') will parse based on UTC time, and the date/time will be adjusted to the user's time zone.  So for anyone west of the Greenwich Meridian, their date will be adjusted back to an earlier time. Even one hour west of UTC will result in one day previous. 

In my tests, Datepicker will populate correctly based on the form field value so the script doesn't need to try to set the date. But if it does, it could do it explicitly rather than having JavaScript parse. Like this: new Date(2017, 1 - 1, 27);. Note that the month is zero based.

I fixed this without touching the files using a hack - a new plugin that registers a low priority script that runs after the deadline.js script and just resets the date to the correct one based on the form field value.

**Comment by spencerfinnell** [comment]
Closing for https://github.com/Automattic/WP-Job-Manager/issues/869
