### ISSUE TITLE
Expiration date function bugging / Job Listings disabling

### ISSUE THREAD

**Issue by WietzeKleisterlee** [Automattic/WP-Job-Manager#858]
#### What I Expected To Happen
I expect the backend summary page of all job listings to show the correct expiration date per job listing and the job listings to show on the front end.

#### What Happened Instead
Expiration date in the backend showing 1-1-1970 on all job listings in the summary page, even when changed by editing the job listing, it does show up on the front-end.

Update1: The job listings expire once every so often (I just set the dates to somewhere in march about an hour ago, (of course the Summary expiration date did not update, but the listings were showing on the front and had a green tick) went for dinner and had another look after and they had all disabled)

Update2: Noticed when editing a single job listing the year isn't being picked up (it keeps saying "jj") when using the date picker (maybe it has something to do with my site being Dutch/in the Dutch language ?)

When putting it in by hand the expiration date shows on the summary as well, will look wether or not it disables itself after some time again)

#### Steps to Reproduce the Bug
Don't exactly know, some background information: using Themify Ultra theme (Themify.me) Contactform 7, Wordfence & Yoast SEO plugins (maybe there's a conflict?)

**Comment by Draxeiro** [comment]
This bug had previously been fixed (see issue #697), however since the recent update to Wordpress 4.7.1 it is back again.

Picking the date via the date picker will result in the listing date not being added properly (the date will show correctly until the listing is saved. The summary page will indeed show 1-1-1970 as the date and on the job listing page itself the date will be in the past (so the listing will not show any more).

Filling in the date by hand will work as a temporary workaround.

**Comment by spencerfinnell** [comment]
Closing for https://github.com/Automattic/WP-Job-Manager/issues/869
