### ISSUE TITLE
WP Job Manager Subscription error

### ISSUE THREAD

**Issue by mmak0710** [Automattic/WP-Job-Manager#925]

**Comment by manfredinicolas** [comment]
+1

**Comment by codep0et** [comment]
+1 here also, same here on woocommerce 3

**Comment by stantyan** [comment]
+1
same issue

**Comment by Brayds** [comment]
I'm having the same issue because of the above. 

When it comes time for the user to "Select a package" nothing is displaying as all products that were "Job Subscription Packages" have rolled back to "Simple Subscription" with no way to change them to "Job Subscription package" and save changes. Changes don't save.

**Comment by codep0et** [comment]
Support was contacted, its related to the plugin wp job manager paid listing. They are working on an update that will come out very soon they said to fix this issue

**Comment by bepbrasil** [comment]
Anyone knows when this fix will be released?

**Comment by codep0et** [comment]
@bepbrasil If you have a valid license and contact support they will send you the current zip with the fix

**Comment by harshinisri** [comment]
I am also having this same issue.

**Comment by jom** [comment]
@harishankerr Have you updated to WP Job Manager - WC Paid Listings v2.7.2?

**Comment by harshinisri** [comment]
that worked! thankyou so much!
