### ISSUE TITLE
Change 'Resume' to 'CV' for English UK

### ISSUE THREAD

**Issue by owbrennan** [Automattic/WP-Job-Manager#966]
Would it be possible for you to add in an option to change 'Resume' to 'CV' across the site, as this is what they are more commonly referred to In the UK.

Obviously I can go and manually edit all the occurrences, but then it will be overwritten next time you guys release an update. I thought I'd raise it as I can't be the only person in this position.

If you could indicate whether this would be something you will look at that would be great, otherwise I'll do it manually.

Thanks for the effort in creating a great product!

Oli

**Comment by jom** [comment]
Hi there! The resume plugin is localization-ready. Instead of changing the actual plugin, you can create a translation for `en_GB`. I'd recommend using a WordPress plugin like Loco Translate. When creating a new translation for the Resume Manager, store the files under the `system` option. Changes to the plugin won't remove your translations (although new/modified strings in the plugin will have to be translated. This will also allow you to change other UK spelling variations.

Feel free to contribute your translations back to the project. If you'd like to do that, ping me on this issue and we can arrange the transfer of the `.mo` and `.po` files. 

Screenshot of what the set up looks like in Loco Translate:
<img width="847" alt="screen shot 2017-05-15 at 3 37 39 pm" src="https://cloud.githubusercontent.com/assets/68693/26063039/a80479d8-3984-11e7-8d8a-0380ce7d45c2.png">
