### ISSUE TITLE
Refactor `[jobs]` shortcode to work without need of Ajax when necessary/requested

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#997]
The `[jobs]` shortcode's form should work without the need for JavaScript/Ajax when necessary. It should fail gracefully and behave like a normal form/pagination if JavaScript is disabled or a robot who doesn't like JavaScript visits. Additionally, a filter should be added so that a user can disable the use of loading jobs via Ajax altogether.

**Comment by RiaanKnoetze** [comment]
@jom - Did this make it to 1.27? Just worked through the changelog but couldn't immediately see anything :)

**Comment by jom** [comment]
Nope, it is targeted for 1.28.0.

**Comment by tomslominski** [comment]
Hey. Listify suggested I add this suggestion here - would you be able to make it so that search criteria is reflected in the URL? My clients have asked if its possible that a particular set of search criteria can be shared as a URL - for example, if I do a search on our site which returns four restaurants (we use Job Manager & Listify for a restaurants listing site), I should be able to text that link to a friend for them to have a look at the same set of results.

It seems to appropriate to mention it here, since making the form work without JS would likely require search parameters to be passed through the URL.

**Comment by tsanren89** [comment]
+1
Wish to have this also.

**Comment by jom** [comment]
Deferring this to the work we'll be doing for the jobs block.
